[aws]
region = "us-east-1"
user_pool_id = "us-east-1_GAijvrCZO"
client_id = "5fl3q5trajhndpvdgd6ur3a39k"
client_secret = "70vpv2dcdkgmn9ogslv8vvs4136c942qecu4k5c580vk0tf5c2n"

[database]
host = "attendance-db.cari4oa424ti.us-east-1.rds.amazonaws.com"
user = "admin"
password = "Tracker-2026"
database = "attendance_db"
